name: Generate Permanent Keystore

on:
  workflow_dispatch: # Allows you to trigger it manually with a button click

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore via Keytool
        run: |
          keytool -genkeypair -v \
            -keystore sonora-release.jks \
            -alias sonora_key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "Sonora@1912" \
            -keypass "SonoraSecretPass123" \
            -dname "CN=Sonora, OU=Mobile, O=Sonora, L=Mumbai, ST=Maharashtra, C=IN"

      - name: Upload Keystore as Artifact (Download to your PC for safekeeping)
        uses: actions/upload-artifact@v4
        with:
          name: sonora-keystore-backup
          path: sonora-release.jks

      - name: Print Base64 String
        run: |
          echo "====================== COPY BELOW THIS LINE ======================"
          base64 -w 0 sonora-release.jks
          echo ""
          echo "====================== COPY ABOVE THIS LINE ======================"
